import type { Stack } from 'aws-cdk-lib';
import { NagSuppressions } from 'cdk-nag';

/**
 * CDK synthesizes a handful of helper resources (custom-resource providers) that
 * the application never sees or controls — their roles, runtimes, and wildcard
 * policies are managed entirely by the CDK framework. These cannot be hardened
 * by the consumer, so each is suppressed here with an explicit, audit-ready
 * justification. This is the only place such framework suppressions live.
 */
const CDK_MANAGED_PROVIDER_PATHS = [
    // S3 auto-delete-objects custom resource (present when a bucket uses DESTROY removal).
    'Custom::S3AutoDeleteObjectsCustomResourceProvider',
    // Restrict-default-security-group custom resource (restrictDefaultSecurityGroup flag).
    'Custom::VpcRestrictDefaultSGCustomResourceProvider',
];

const CDK_MANAGED_SUPPRESSIONS = [
    {
        id: 'AwsSolutions-IAM4',
        reason: 'CDK framework-managed custom-resource provider; its role uses the AWS-managed basic Lambda execution policy and is not consumer-configurable.',
    },
    {
        id: 'AwsSolutions-IAM5',
        reason: 'CDK framework-managed custom-resource provider; wildcards are scoped to the owning resource and generated by CDK, not by application code.',
    },
    {
        id: 'AwsSolutions-L1',
        reason: 'CDK framework-managed custom-resource provider; its Lambda runtime is pinned and upgraded by the CDK library, not by the consumer.',
    },
];

/**
 * Apply documented suppressions to CDK framework-managed helper resources in a
 * stack. Safe to call on every stack; paths that are not present are skipped.
 */
export function suppressCdkManagedResources(stack: Stack): void {
    for (const path of CDK_MANAGED_PROVIDER_PATHS) {
        const fullPath = `${stack.node.path}/${path}`;
        try {
            NagSuppressions.addResourceSuppressionsByPath(
                stack,
                fullPath,
                CDK_MANAGED_SUPPRESSIONS,
                true,
            );
        } catch {
            // Path not present in this stack — nothing to suppress.
        }
    }
}
